### ISSUE TITLE
Add JSON schema for configuration files

### ISSUE THREAD

**Issue by matt-graham** [high-dimensional/3d_very_deep_vae#18]
It would be good to full document all of the properties that can be set in the configuration JSON files with descriptions of each possible field and their expected types. Doing this as a [JSON Schema](https://json-schema.org/) file would both allow us to automate generating corresponding human-readable documentation and also allow validating configuration files against the schema before running for example using the [Python `jsonschema` package](https://github.com/python-jsonschema/jsonschema).

**Comment by matt-graham** [comment]
I have started documenting the configuration file options [in the wiki](https://github.com/high-dimensional/3d_very_deep_vae/wiki/Configuration-file-options) in preparation for creating a JSON Schema.

**Comment by high-dimensional-admin** [comment]
I have had a go at filling in the remaining fields - please let me know if there is anything outstanding!
