### ISSUE TITLE
Undefined names in `verydeepvae.data_tools.data_transformations_2d` module

### ISSUE THREAD

**Issue by matt-graham** [high-dimensional/3d_very_deep_vae#28]
The `verydeepvae.data_tools.data_transformations_2d` module contains this snippet of code

https://github.com/high-dimensional/3d_very_deep_vae/blob/b8c4763a12a8da16885c16245e9591fc37d59734/verydeepvae/data_tools/data_transformations_2d.py#L54-L61

in which the nams `SimulateMissingnessAugmentation`, `LoadJSONd` and `SimulateJSONMissingnessAugmentation` are all not previously defined. They also all do not seem to be defined anywhere else in the codebase.

The single `create_data_transformations_2d` function in this module is not currently called anywhere - @r-gray should this just be removed?

**Comment by high-dimensional-admin** [comment]
Yep, quite right Matt, the code block above, and the function create_data_transformations_2d, are only relevant to a fork of this code - they can indeed both be deleted!
