### ISSUE TITLE
Name `data_dictionary_latents` undefined in `gaussian_output` function

### ISSUE THREAD

**Issue by matt-graham** [high-dimensional/3d_very_deep_vae#29]
In the `gaussian_output` function in the `verydeepvae.misc.misc` module, a reference is made to `data_dictionary_latents` variable which has previously not been defined

https://github.com/high-dimensional/3d_very_deep_vae/blob/b8c4763a12a8da16885c16245e9591fc37d59734/verydeepvae/misc/misc.py#L122-L140

@r-gray should this instead refer to the `data_dictionary_x_mu` argument?

**Comment by high-dimensional-admin** [comment]
Hi Matt, yep, as discussed earlier I think you're right that adding data_dictionary_latents as an input argument to gaussian_output is probably the best way to solve this. It's true that to keep memory usage to a minimum I rarely (if ever) activate hyper_params['separate_output_loc_scale_convs'], but it would be quite a bit of unnecessary work to remove the ability to predict locations and scales with different neural nets, which is what this option does, and it's a nice feature to have if there are spare GBs on the GPU...
